### ISSUE TITLE
setup remote wss connection for client 

### ISSUE THREAD

**Issue by chaosma** [e2chain-dev/e2-chain#2]
Follow this to setup: https://wiki.polkadot.network/docs/en/maintain-wss

Currently we have a blockchain with 3 nodes. I setup wss certificate with one of the node so that we can access the [polkadot.js.org/apps/#/explorer](polkadot.js.org/apps/#/explorer) remotely.

I found the chrome browser cannot proceed for the self-signed certificate (probably need some setting change). but firefox and safari can proceed. However, still cannot connect to the remote node from explorer:

put  wss://<server_ip>:9944 into Development -> Custom (in polkadot.js.org/apps) . it gave error: You are not connected to a node. Ensure that your node is running and that the Websocket endpoint is reachable.  And in console:  API-WS: disconnected from wss://138.68.229.14:9944: 1006:: Abnormal Closure.

**Comment by lzw65** [comment]
Put wss://138.68.229.14 to the custorm endpoint, you can connect to the remote node from chrome browser. But firefox cannot work well.

**Comment by lzw65** [comment]
> Put wss://138.68.229.14 to the custorm endpoint, you can connect to the remote node from chrome browser. But firefox cannot work well.

When we start node ,  add  "--rpc-cors all".

**Comment by chaosma** [comment]
use port 443 instead.
