### ISSUE TITLE
Error in Balance display on  https://polkadot.js.org/apps

### ISSUE THREAD

**Issue by lzw65** [e2chain-dev/e2-chain#5]
We use Polkadot.js.org/apps to connect to e2-chain, the balance of acountid is wrong.

**Comment by chaosma** [comment]
After investigation, we can use an old commit version of polkadot.js.org/aps to solve the problem.  for example: d4cc760462eb7740b29a997d1004497c9916f824  will solve the problem.  For the exact reason, why the new version cannot show balance, need further investigation.

**Comment by lzw65** [comment]
According to polkadot.js.org/apps releases history on page 'https://github.com/polkadot-js/apps/releases',  we find out that apps start to use @polkadot/api 2.0.1 from V0.60.1. After investigation, we find v0.59.1 can show balance correctly, but v0.60.1 doesn't.

**Comment by lzw65** [comment]
> According to polkadot.js.org/apps releases history on page 'https://github.com/polkadot-js/apps/releases', we find out that apps start to use @polkadot/api 2.0.1 from V0.60.1. After investigation, we find v0.59.1 can show balance correctly, but v0.60.1 doesn't.

However, no matter what polkadot.js.org/apps version we use , we cann't make transfer. 
At present,  the only corrective client is Subtrate-front-end-template with @polkadot/api: ^1.34.1 in the package.json. Under this condtion, we can make transfer and get balance correctly.
